In [1]:
import numpy as np

## 求最值

In [4]:
X = np.arange(1000)

In [6]:
X.max()

999

In [8]:
X.min()

0

In [12]:
Y = X.reshape(5, -1)
Y

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [14]:
np.min(Y, axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [15]:
np.min(Y, axis = 1)

array([  0, 200, 400, 600, 800])

## 求总和

In [16]:
np.sum(Y)

499500

In [17]:
np.sum(Y, axis = 0)

array([2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050,
       2055, 2060, 2065, 2070, 2075, 2080, 2085, 2090, 2095, 2100, 2105,
       2110, 2115, 2120, 2125, 2130, 2135, 2140, 2145, 2150, 2155, 2160,
       2165, 2170, 2175, 2180, 2185, 2190, 2195, 2200, 2205, 2210, 2215,
       2220, 2225, 2230, 2235, 2240, 2245, 2250, 2255, 2260, 2265, 2270,
       2275, 2280, 2285, 2290, 2295, 2300, 2305, 2310, 2315, 2320, 2325,
       2330, 2335, 2340, 2345, 2350, 2355, 2360, 2365, 2370, 2375, 2380,
       2385, 2390, 2395, 2400, 2405, 2410, 2415, 2420, 2425, 2430, 2435,
       2440, 2445, 2450, 2455, 2460, 2465, 2470, 2475, 2480, 2485, 2490,
       2495, 2500, 2505, 2510, 2515, 2520, 2525, 2530, 2535, 2540, 2545,
       2550, 2555, 2560, 2565, 2570, 2575, 2580, 2585, 2590, 2595, 2600,
       2605, 2610, 2615, 2620, 2625, 2630, 2635, 2640, 2645, 2650, 2655,
       2660, 2665, 2670, 2675, 2680, 2685, 2690, 2695, 2700, 2705, 2710,
       2715, 2720, 2725, 2730, 2735, 2740, 2745, 27

In [18]:
np.sum(Y, axis = 1)

array([ 19900,  59900,  99900, 139900, 179900])

## 求均值

In [19]:
np.mean(Y)

499.5

## 求中位数

In [22]:
np.median(Y)

499.5

## 求标准差

In [23]:
np.std(Y)

288.6749902572095

## 求方差

In [24]:
np.var(Y)

83333.25

## 最大值与最小值的差

In [25]:
np.ptp(Y)

999

## 百分位数，中位数就是50%位的数

In [38]:
q = np.linspace(0, 100, 5)
q, np.percentile(Y, q)

(array([  0.,  25.,  50.,  75., 100.]),
 array([  0.  , 249.75, 499.5 , 749.25, 999.  ]))

## 累加

In [39]:
np.cumsum(Y, axis=0)

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
          55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
          66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
          77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
          88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
          99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
         110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
         121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
         132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
         143,  144,  145,  146,  147, 

In [40]:
np.cumsum(Y, axis=1)

array([[     0,      1,      3,      6,     10,     15,     21,     28,
            36,     45,     55,     66,     78,     91,    105,    120,
           136,    153,    171,    190,    210,    231,    253,    276,
           300,    325,    351,    378,    406,    435,    465,    496,
           528,    561,    595,    630,    666,    703,    741,    780,
           820,    861,    903,    946,    990,   1035,   1081,   1128,
          1176,   1225,   1275,   1326,   1378,   1431,   1485,   1540,
          1596,   1653,   1711,   1770,   1830,   1891,   1953,   2016,
          2080,   2145,   2211,   2278,   2346,   2415,   2485,   2556,
          2628,   2701,   2775,   2850,   2926,   3003,   3081,   3160,
          3240,   3321,   3403,   3486,   3570,   3655,   3741,   3828,
          3916,   4005,   4095,   4186,   4278,   4371,   4465,   4560,
          4656,   4753,   4851,   4950,   5050,   5151,   5253,   5356,
          5460,   5565,   5671,   5778,   5886,   5995,   6105, 

## 相邻的差 

In [42]:
np.diff(Y, axis = 0)

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200

In [43]:
np.cumsum(Y, axis=1)

array([[     0,      1,      3,      6,     10,     15,     21,     28,
            36,     45,     55,     66,     78,     91,    105,    120,
           136,    153,    171,    190,    210,    231,    253,    276,
           300,    325,    351,    378,    406,    435,    465,    496,
           528,    561,    595,    630,    666,    703,    741,    780,
           820,    861,    903,    946,    990,   1035,   1081,   1128,
          1176,   1225,   1275,   1326,   1378,   1431,   1485,   1540,
          1596,   1653,   1711,   1770,   1830,   1891,   1953,   2016,
          2080,   2145,   2211,   2278,   2346,   2415,   2485,   2556,
          2628,   2701,   2775,   2850,   2926,   3003,   3081,   3160,
          3240,   3321,   3403,   3486,   3570,   3655,   3741,   3828,
          3916,   4005,   4095,   4186,   4278,   4371,   4465,   4560,
          4656,   4753,   4851,   4950,   5050,   5151,   5253,   5356,
          5460,   5565,   5671,   5778,   5886,   5995,   6105, 

## 乘积

In [44]:
np.prod(Y)

0

In [50]:
Y, np.prod(Y, axis = 0)

(array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
         169, 170, 171, 172, 173, 174,