# 导入Numpy

In [1]:
import numpy as np

# 创建Numpy数组

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy数组的属性

In [5]:
a.ndim

1

In [6]:
A.ndim

2

In [7]:
a.shape

(6,)

In [8]:
A.shape

(2, 3)

In [9]:
a.size

6

In [10]:
A.size

6

In [12]:
a.dtype

dtype('int32')

In [13]:
A.dtype

dtype('int32')

# 创建数组的便捷方法

## ones

In [14]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(8).dtype

dtype('float64')

In [16]:
np.ones(8, dtype='int64').dtype

dtype('int64')

In [17]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones_like(A)  # 大小相同的数组

array([[1, 1, 1],
       [1, 1, 1]])

## zeros

In [21]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## full

In [26]:
np.full(8, 666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [27]:
np.full((2,8), 666)

array([[666, 666, 666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666, 666, 666]])

In [28]:
np.full_like(A, 666)

array([[666, 666, 666],
       [666, 666, 666]])

## empty

In [30]:
np.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 8.75484324e-321, 3.11525958e-307, 1.24610723e-306])

In [31]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.75484324e-321, 3.11525958e-307,
        1.24610723e-306]])

In [32]:
np.empty_like(A)

array([[   1772,       0,       0],
       [4980828,       0, 7077985]])

## arange

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## linspace 等差数组

In [39]:
np.linspace(0,10,5) # 0-10 生成5的元素等差

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random 模块

## random

In [40]:
np.random.random()

0.7428846740723585

In [41]:
np.random.random(5)

array([0.75216133, 0.07290595, 0.9364185 , 0.96970298, 0.17482907])

In [42]:
np.random.random((2,4))

array([[0.9264773 , 0.47472838, 0.56614784, 0.97250282],
       [0.31574792, 0.52506048, 0.47082206, 0.52792551]])

## rand

In [43]:
np.random.rand()

0.832183393540349

In [44]:
np.random.rand(5)

array([0.69433065, 0.90279431, 0.63949643, 0.27063554, 0.20005776])

In [46]:
np.random.rand(2,4)

array([[0.22236117, 0.46802989, 0.32003989, 0.0342868 ],
       [0.38981725, 0.33135556, 0.49577343, 0.74295834]])

## randint

In [47]:
np.random.randint(5)

3

In [49]:
np.random.randint(5,10)

9

In [50]:
np.random.randint(5,10,size=8)

array([8, 5, 7, 8, 8, 7, 9, 8])

In [51]:
np.random.randint(5,10,size=(2,4))

array([[8, 8, 5, 6],
       [7, 6, 8, 5]])

## seed

In [61]:
np.random.seed(666)
np.random.randint(5,10,size=(2,4))

array([[9, 7, 6, 9],
       [8, 8, 9, 9]])

## randn

In [64]:
np.random.randn(5)

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])

In [65]:
np.random.randn(2,4)

array([[ 1.58248112, -0.9092324 , -0.59163666,  0.18760323],
       [-0.32986996, -1.19276461, -0.20487651, -0.35882895]])

## normal

In [68]:
np.random.normal()  # 均值是0，标准差是1

-1.6647885294716944

In [70]:
np.random.normal(10, 1000, 20)  # 均值是10，标准差是1000

array([ -690.17903769,  1161.39100949,  1867.33100723, -1501.17955769,
         654.84751089,  -970.60788522,  -846.85315472,  -861.87918326,
        -412.50792916,  1006.43982691,   722.42127088,    69.14424322,
        -353.31087848,    13.28884293,   -95.93044206,   803.05331946,
        -621.57162979,     3.80509151,   -91.06761181,   -42.30815085])

In [71]:
np.random.normal(10, 1000, size=(2,4)) 

array([[ 259.21765856,  207.66009104, 1344.84857424,  -76.87560628],
       [1571.53229345, -295.85302117, -467.73141728,  110.73818875]])

## uniform

In [73]:
np.random.uniform()

0.8166602026153619

In [76]:
np.random.uniform(1, 5)

4.2476095647216425

In [75]:
np.random.uniform(1.5, 4)

3.0883905139547325

In [77]:
np.random.uniform(1, 5, (3,4))

array([[4.70673046, 4.65050705, 4.29924288, 1.37681093],
       [2.44419367, 1.14203613, 3.18543339, 4.18457088],
       [1.20457121, 1.75467094, 2.46191107, 1.97716347]])

# 查阅文档
比如忘了uniform是什么

In [80]:
np.random.uniform?

In [79]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high