In [1]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
[x[2],x[5],x[8]]

[2, 5, 8]

In [7]:
# 也可以直接传索引数组
index = [2,5,8]
x[index]

array([2, 5, 8])

In [8]:
index = np.array([
    [0,2,4],
    [1,3,5]
])
x[index]

array([[0, 2, 4],
       [1, 3, 5]])

## 神奇数组应用与二维数组

In [9]:
X = x.reshape(2, -1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
row = [0, 1, 0]
col = [1, 2 , 3]
X[row, col]

array([1, 7, 3])

In [12]:
X[0, col]

array([1, 2, 3])

In [13]:
X[row, :2]

array([[0, 1],
       [5, 6],
       [0, 1]])

## 使用布尔数组

In [15]:
col = [True, False, True, False, False]
X[0, col]

array([0, 2])

## 比较 & 布尔数组与神奇索引的使用

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x < 2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [18]:
x[x<2]

array([0, 1])

In [19]:
x*x == 9

array([False, False, False,  True, False, False, False, False, False,
       False])

In [20]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
X < 3

array([[ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [22]:
X [X<3]

array([0, 1, 2])

## 比较的更多应用

In [23]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.count_nonzero(x)

9

In [25]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [28]:
np.count_nonzero(x<5) # 相当于将布尔数组的true看成1

5

In [29]:
np.sum(x<5)

5

In [35]:
np.any(x<0) # 判断数组至少有一个True

False

In [36]:
np.any(x>5)

True

In [37]:
np.all(x>0) # 判断数组都是True

False

In [38]:
np.all(x<10)

True

In [39]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
np.sum(X, axis = 1)

array([10, 35])

In [41]:
np.sum(X<2, axis = 1)

array([2, 0])

## 与& 或| 非~

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.sum((x<5)&(x>1))

3