In [1]:
import numpy as np

In [4]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
Y = X*2
Y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 一元运算

In [15]:
X = np.arange(1, 11, 0.5).reshape(4,5)
X

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [16]:
np.abs(X)

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [17]:
np.sqrt(X)

array([[1.        , 1.22474487, 1.41421356, 1.58113883, 1.73205081],
       [1.87082869, 2.        , 2.12132034, 2.23606798, 2.34520788],
       [2.44948974, 2.54950976, 2.64575131, 2.73861279, 2.82842712],
       [2.91547595, 3.        , 3.082207  , 3.16227766, 3.24037035]])

In [18]:
np.square(X)

array([[  1.  ,   2.25,   4.  ,   6.25,   9.  ],
       [ 12.25,  16.  ,  20.25,  25.  ,  30.25],
       [ 36.  ,  42.25,  49.  ,  56.25,  64.  ],
       [ 72.25,  81.  ,  90.25, 100.  , 110.25]])

In [19]:
np.exp(X)

array([[2.71828183e+00, 4.48168907e+00, 7.38905610e+00, 1.21824940e+01,
        2.00855369e+01],
       [3.31154520e+01, 5.45981500e+01, 9.00171313e+01, 1.48413159e+02,
        2.44691932e+02],
       [4.03428793e+02, 6.65141633e+02, 1.09663316e+03, 1.80804241e+03,
        2.98095799e+03],
       [4.91476884e+03, 8.10308393e+03, 1.33597268e+04, 2.20264658e+04,
        3.63155027e+04]])

In [20]:
np.log(X)

array([[0.        , 0.40546511, 0.69314718, 0.91629073, 1.09861229],
       [1.25276297, 1.38629436, 1.5040774 , 1.60943791, 1.70474809],
       [1.79175947, 1.87180218, 1.94591015, 2.01490302, 2.07944154],
       [2.14006616, 2.19722458, 2.2512918 , 2.30258509, 2.35137526]])

In [21]:
np.log2(X)

array([[0.        , 0.5849625 , 1.        , 1.32192809, 1.5849625 ],
       [1.80735492, 2.        , 2.169925  , 2.32192809, 2.45943162],
       [2.5849625 , 2.70043972, 2.80735492, 2.9068906 , 3.        ],
       [3.08746284, 3.169925  , 3.24792751, 3.32192809, 3.39231742]])

In [22]:
np.log10(X)

array([[0.        , 0.17609126, 0.30103   , 0.39794001, 0.47712125],
       [0.54406804, 0.60205999, 0.65321251, 0.69897   , 0.74036269],
       [0.77815125, 0.81291336, 0.84509804, 0.87506126, 0.90308999],
       [0.92941893, 0.95424251, 0.97772361, 1.        , 1.0211893 ]])

In [23]:
X

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [24]:
np.ceil(X)

array([[ 1.,  2.,  2.,  3.,  3.],
       [ 4.,  4.,  5.,  5.,  6.],
       [ 6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11.]])

In [25]:
np.floor(X)

array([[ 1.,  1.,  2.,  2.,  3.],
       [ 3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.],
       [ 8.,  9.,  9., 10., 10.]])

In [26]:
np.round(X)

array([[ 1.,  2.,  2.,  2.,  3.],
       [ 4.,  4.,  4.,  5.,  6.],
       [ 6.,  6.,  7.,  8.,  8.],
       [ 8.,  9., 10., 10., 10.]])

## 二元运算

In [27]:
X+1

array([[ 2. ,  2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. , 11.5]])

In [28]:
np.add(X,1)

array([[ 2. ,  2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. , 11.5]])

In [29]:
X*2

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.]])

In [31]:
X**2

array([[  1.  ,   2.25,   4.  ,   6.25,   9.  ],
       [ 12.25,  16.  ,  20.25,  25.  ,  30.25],
       [ 36.  ,  42.25,  49.  ,  56.25,  64.  ],
       [ 72.25,  81.  ,  90.25, 100.  , 110.25]])

In [32]:
X/2

array([[0.5 , 0.75, 1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25, 2.5 , 2.75],
       [3.  , 3.25, 3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75, 5.  , 5.25]])

In [33]:
X//2

array([[0., 0., 1., 1., 1.],
       [1., 2., 2., 2., 2.],
       [3., 3., 3., 3., 4.],
       [4., 4., 4., 5., 5.]])

In [34]:
2/X

array([[2.        , 1.33333333, 1.        , 0.8       , 0.66666667],
       [0.57142857, 0.5       , 0.44444444, 0.4       , 0.36363636],
       [0.33333333, 0.30769231, 0.28571429, 0.26666667, 0.25      ],
       [0.23529412, 0.22222222, 0.21052632, 0.2       , 0.19047619]])

## 矩阵运算

In [35]:
X = np.linspace(10, 40, 4).reshape(2,2)
Y = np.linspace(1, 4, 4).reshape(2,2)

In [36]:
X

array([[10., 20.],
       [30., 40.]])

In [37]:
Y

array([[1., 2.],
       [3., 4.]])

In [38]:
X+Y

array([[11., 22.],
       [33., 44.]])

In [39]:
X-Y

array([[ 9., 18.],
       [27., 36.]])

In [40]:
X*Y # 哈达玛积

array([[ 10.,  40.],
       [ 90., 160.]])

In [42]:
X.dot(Y) # 真正的矩阵相乘

array([[ 70., 100.],
       [150., 220.]])

In [43]:
X/Y

array([[10., 10.],
       [10., 10.]])

In [44]:
X.T

array([[10., 30.],
       [20., 40.]])

In [45]:
np.transpose(X)

array([[10., 30.],
       [20., 40.]])

In [47]:
np.linalg.inv(X) # 逆矩阵

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [48]:
np.linalg.det(X) # 特征向量

-200.0000000000001